### PR TITLE
Downgrade Node.js to fix builds on Travis CI

### PR DESCRIPTION
**Pull request by meisenzahl**

### CODE REVIEW

**Comment by dahenson** [comment]
Thanks for this. I was not aware that the Node version was breaking builds, but I see that a lot of elementary apps are following suit.

**Comment by ryonakano** [comment]
It looks like the [`debian/rules`](https://github.com/dahenson/agenda/blob/deb-packaging/debian/rules) file says to use Meson to build the project, while the project uses CMake. This seems to be another reason the build still fails.
See also: https://travis-ci.org/dahenson/agenda/builds/609370768#L3424

**Comment by dahenson** [comment]
I am currently only concerned with getting the `develop` branch to build, which actually has meson as the build system. Once I can get that to build and I'm confident in a stable release, I will merge the `develop` branch into `master`

**Comment by ryonakano** [comment]
@dahenson I guess you should merge `master` into `develop` to reflect the changes in this PR then.

**Pull request merged**
